name: maplibre_style_spec
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.6.0-334.2.beta

dependencies:
  collection: ^1.19.0
  csslib: ^1.0.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  analyzer: ^6.11.0
